name: my_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  http: ^1.2.1
  flash_light_control_plugin:
    git:
      url: https://github.com/wertylu/flashlight.git

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/vr38dett_engine.jpg
    - assets/placeholder.png

  uses-material-design: true

