name: my_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  url_launcher: ^6.2.5
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.0.0+2
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.2
  provider: ^6.1.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/vr38dett_engine.jpg
    - assets/placeholder.png

  uses-material-design: true

